### ISSUE TITLE
would not build on eosio version 1.4

### ISSUE THREAD

**Issue by shellinspector** [operanditech/token_ram_recovery#1]
Hello Andres,
I was very happy to find your solution to recover RAM from contract tables. However as of december 2018 the contract code does not build to various issues. I am looking into it myself trying to fix it, however with my skills it might take considerably longer. Could I please ask you to update your code to the latest eosio version? Preferably to be built using cmake.

Thanks,
Maxim

**Comment by andresberrios** [comment]
Hi Maxim,
I'll look into it in the next few days.

**Comment by shellinspector** [comment]
Andres,
I am wondering, if the goal is to remove entries in records, the fact that you set new contract (token_ram_recovery) into an account that previously hosted  another contract (eosio.token) will remove all multiindex tables that belonged to an old account. Multiindex tables should not exist without the contract which created and maintained them. Correct? As soon as I uploaded your token_ram_recovery.wasm to my account that had eosio.token contract I can no longer see the stat table:
```
Error 3060003: Contract Table Query Exception
Most likely, the given table doesn't exist in the blockchain.
Error Details:
Table stat is not specified in the ABI
```
So the multiindex is apparently very sensitive, if someone uploads some new contract, all database will be wiped out!  RAM is recovered the easy way :)

**Comment by shellinspector** [comment]
..me again, just uploaded back the eosio.token contract  after removing it, and all my table entries are back. Seems like you can't remove or free table entries using another smart contract. Unless the original sm. contract does not provide an action to remove entries, the table data will stay there forever. Please correct me if I am wrong. They must have done this provision in the latest versions of eosio , while token_ram_recovery must have been working with an older more allowing version.

**Comment by andresberrios** [comment]
@shellinspector let me explain:

- The data you insert into tables in a contract will remain there until you explicitly remove it using code.
- A contract can read tables from any other account and write only to the ones in its own account.
- These tables exist whether or not you are able to see them when querying through `cleos` or `eosjs` from the HTTP endpoint of `nodeos`.
  - This is because they will only be queryable this way if they are defined in the ABI file that is uploaded to the account next to the contract code.
- Uploading a different contract doesn't change the data that is stored in the DB.
- Uploading a different ABI changes what tables you can externally query from the DB, but it doesn't change the underlying data that is stored.
- Nothing of this has changed in the EOSIO software since launch.
- **You can upload a new contract that provides code to erase data that was inserted into tables in a previously deployed contract.** This is what this contract does for any token contract that follows the structure of the standard `eosio.token`.

You can compile this contract using the old `eosiocpp` compiler and it will work fine in new versions of EOSIO since what has changed is only some of the library APIs but none of the intrinsics with which you interact with the chain and database. I'll look into updating this code to use the new version anyway, just to keep it fresh.

If you manage to compile it using the old compiler, make sure to also deploy the ABI file so you can query the tables.
